### PR TITLE
Declare stylelint version as a peerDependencies in package.json

### PR DESCRIPTION
**Pull request by ntwb**
See #12

### CODE REVIEW

**Comment by jeddy3** [comment]
@Arcanemagus @ntwb Thanks for this.

Before I merge this in I wanted to double checking something... this config now supports `4.5.x` and `5.0.0`. Is the peer dependency in this PR still correct, or will it need to be changed?

**Comment by Arcanemagus** [comment]
It will need to be changed, `^4.5.0` is the equivalent of writing `>=4.5.0 <5.0.0`.

**Comment by Arcanemagus** [comment]
It looks like probably the best string to put in there is `>=4.5.0 <6.0.0` as we can't use the `^` shortcut easily, but there is probably a better way of writing that that I just don't know about :stuck_out_tongue:.

**Comment by jeddy3** [comment]
@Arcanemagus Thanks! Done in https://github.com/stylelint/stylelint-config-standard/commit/f9a7079e36c145122e3fea14dfc889c20a9b1b7c.

**Comment by ntwb** [comment]
Apologies, where I travelled to this weekend I thought it'd have internet access, turns out I was a little further in outback Australia than I thought :smirk:

**Pull request merged**
