### PR TITLE
refactor: Extend `stylelint-config-recommended`

### PR DESCRIPTION
**Pull request by ntwb**
Per #2704:
> _"I anticipate stylelint-config-standard will extend stylelint-config-recommended, and apply its current set of stylistic rules."_

This PR implements the above change.

### CODE REVIEW

**Comment by jeddy3** [comment]
Fantastic timing. I was _just_ about to do this myself to follow up https://github.com/stylelint/stylelint/pull/2727!

**Comment by ntwb** [comment]
Not sure why only Node.js 8.x branch failed:
• https://travis-ci.org/stylelint/stylelint-config-standard/jobs/252196308

Restarting the job now

**Comment by jeddy3** [comment]
Shall I publish a `1.0.0` of `stylelint-config-recommended` to see if that'll help?

**Comment by hudochenkov** [comment]
npm install:

```
└── UNMET DEPENDENCY stylelint-config-recommended@^0.1.0
npm ERR! missing: stylelint-config-recommended@^0.1.0, required by stylelint-config-standard@16.0.0
```

npm@5 issue?

**Comment by jeddy3** [comment]
> npm@5 issue?

Likely. I'm wondering if a major release of the recommended config will help npm@5.

**Comment by ntwb** [comment]
@hudochenkov Delete your local `package-lock.json` file

**Comment by hudochenkov** [comment]
@ntwb I use `npm@4`. Log from Travis.

**Comment by ntwb** [comment]
It's not so much a npm 5 issue, we shouldn't be ignoring `package-lock.json` the way we are, which is entirely my fault, I ran out of time today to get some PRs created.

I'm pretty sure I've now got npm 5.x working with 100% compatibility, I'll fix this up for all the stylelint repos in the morning 😄 (It's just gone midnight here)

**Comment by ntwb** [comment]
I've just tested this PR using npm 4.6.1 and Node.js 6.11.0 and it worked without error

**Comment by jeddy3** [comment]
> I've just tested this PR using npm 4.6.1 and Node.js 6.11.0 and it worked without error

Can we merge this?

**Comment by ntwb** [comment]
> So, can we merge this?

I believe we can, that said, I've created #84 to use the latest npm 5.x for all Travis CI jobs, if that passes (I expect it to) I'd like to merge those changes back to this PR and go from there.

**Comment by ntwb** [comment]
Yay, that worked, phew 😏

**Pull request merged**
