### PR TITLE
Update to stylelint 7.6

### PR DESCRIPTION
**Pull request by jeddy3**
@davidtheclark Look good to you?

As always, the tests will fail until `stylelint@7.6` is actually released.

### CODE REVIEW

**Comment by jeddy3** [comment]
Thank you :)

**Comment by ArmorDarks** [comment]
I wonder, why some of rules has been removed? They no longer supported by Stylelint?

**Comment by ntwb** [comment]
@ArmorDarks No, they are still included in stylelint, just those specific rules were removed from this `stylelint-config-standard` shared configuration. 

For some technical information on this decision, see: https://github.com/stylelint/stylelint/issues/2047#issuecomment-261382105

**Comment by ArmorDarks** [comment]
Oh, I see. Worthed to reference this issue in PR's body :)

**Pull request merged**
