### PR TITLE
Fix `value-no-vendor-prefix` for `-webkit-box`

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/stylelint/issues/6372

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
LGTM.

This can be a patch release as it makes the config more permissive.

**Comment by ybiquitous** [comment]
> This can be a patch release as it makes the config more permissive.

Thanks for your review. I agree. 👍🏼

**Comment by Mouvedia** [comment]
> The -webkit-discard value behaves identically to [discard](https://www.w3.org/TR/css-overflow-3/#valdef-continue-discard), except that it only takes effect if the computed value of the [display](https://www.w3.org/TR/css-display-3/#propdef-display) property on the parent is [-webkit-box](https://compat.spec.whatwg.org/#valdef-flex--webkit-box) or [-webkit-inline-box](https://compat.spec.whatwg.org/#valdef-flex--webkit-inline-box) and the computed value of the [-webkit-box-orient](https://compat.spec.whatwg.org/#propdef--webkit-box-orient) property on the parent is vertical.

Then shouldn't we add `inline-box` as well?

**Comment by ybiquitous** [comment]
@Mouvedia Good catch. Can you please open a new pull request to add `inline-box`?

**Comment by Mouvedia** [comment]
@ybiquitous I would if I could include `-webkit-inline-box` but exclude `-moz-inline-box`.
I don't know how to do that using `ignoreValues`.

**Comment by ybiquitous** [comment]
@Mouvedia Indeed, the current rule implementation cannot do it. But that's also true for `-moz-box`, so `inline-box` would be acceptable.

If users hope more strict checks, they can override the config like this:

```json
{
  "extends": ["stylelint-config-standard"],
  "rules": {
    "value-no-vendor-prefix": true
  }
}
```

**Pull request merged**
