### PR TITLE
Bump stylelint-config-recommended version

### LINKED ISSUE #106: update stylelint-config-recommended to support stylelint 9
Hi
I see that you've updated to support stylelint 9, but still requires a dependency on stylelint-config-recommended 2.0.0, which has a dependency on stylelint < 8.
Should update dependency to  stylelint-config-recommended 2.1.0

Thanks.

### PR DESCRIPTION
**Pull request by hudochenkov**
Fixes #106.

I think we could release patch update.

### CODE REVIEW

**Comment by jeddy3** [comment]
When adding/installing this package I get `stylelint-config-recommended@2.1.0` already:

```shell
$ yarn add stylelint-config-standard
yarn add v1.3.2
success Saved 2 new dependencies.
├─ stylelint-config-recommended@2.1.0
└─ stylelint-config-standard@18.1.0
```

Is there something I'm missing here?

**Comment by ntwb** [comment]
This is not required as @jeddy3 has pointed out `stylelint-config-recommended` version `2.1.0` is covered by the semantic version caret in `^2.0.0`

**Comment by ntwb** [comment]
Actually... I take that back, quoting the original report:

> I see that you've updated to support stylelint 9, but still requires a dependency on stylelint-config-recommended 2.0.0, which has a dependency on stylelint < 8.
Should update dependency to stylelint-config-recommended 2.1.0

Technically `stylelint-config-standard` *should* require a minimum of version `2.1.0` of `stylelint-config-recommended` because it includes stylelint version `9.x` changes that are *not* available in stylelint `8.x`

**Comment by ntwb** [comment]
A _minor_ semver bump of `stylelint-config-standard` to version `18.2.0`

**Comment by hudochenkov** [comment]
> Is there something I'm missing here?

There is a case, when `stylelint@8`, `stylelint-config-standard@18.0`, and `stylelint-config-recommended@2.0` were installed. User updates `stylelint` and `stylelint-config-standard` to the latest versions. `stylelint-config-recommended` won't be updated, because 2.0.0 is in range. But 2.0.0 doesn't say anything about `stylelint@9` being peerDependency.

**Comment by jeddy3** [comment]
Interesting. I hadn't considered that case. Thanks for taking the time to explain it.

I'll put out a minor release now.

**Pull request merged**
