### PR TITLE
List unused rules

### LINKED ISSUE #21: List rules that are *NOT* included
I think it would be helpful to me and other consumers of this module to have an up-to-date list of all the stylelint rules that are *not* included in this config. That way I know which ones I need to think about configuring on my own.

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #21 

@davidtheclark This was a very useful suggestion as it forced me to take another look at the rules included in the config.

I’ve added in the `*-no-vendor-prefix` rules. As well as setting a precedence of including `*-case` and `*-no-unknown` rules.

For the list of unused rules, I thought it’d help people if the rules were grouped by purpose. What do you think?

I’m going to see how quickly the other `*-case` and `*-no-unknown` rules get done before doing a release.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Looks great.

I'm not sure, though, about adding the `*-no-vendor-prefix`. Because that rule presumes that you have Autoprefixer in your build, and I'd think we don't want to make that assumption. What was your rationale for adding it?

**Comment by jeddy3** [comment]
> What was your rationale for adding it?

The assumption that *most* people *will be* using autoprefixer. That assumption is based on no data what so ever and in all likelihood it's a bad assumption :)

I've moved them back again and updated the README list accordingly.

**Comment by ntwb** [comment]
@jeddy3 Maybe add in the "Suggested additions" section of the README mention of Autoprefixer, anecdotally I'd also say Autoprefixer usage is pretty high, but if someone doesn't know about it then they won't be using it and once they know about it, I'd say it won't take long before they're using it.

**Comment by jeddy3** [comment]
We already do :)

It's the 3rd item in the list. I have just linkified the text though.

**Comment by ntwb** [comment]
Ha! I missed that, thanks 😏

**Pull request merged**
